version: 2.1

commands:
  print_pl_id:
    description: "As sample command in CI"
    parameters:
      to:
        type: string
    steps:
      - run: echo ${CIRCLECI_WORKFLOW_ID}

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  run_command:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pl_id


workflows:
  welcome:
    jobs:
      - run_command
      
          