version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello

  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world

  print_alias:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo $my_alias_name

  create_env_var:
    docker:
      - image: circleci/node:13.8.0
    environment:
      FOO: bar
    steps:
      - run: echo $FOO

workflows:
  welcome:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print_alias:
          requires:
            - print_world
      - print_env_var