version: 2.1

commands:
  print_pl_id:
    description: "As sample command in CI"
    parameters:
      to:
        type: string
        default: $CIRCLECI_WORKFLOW_ID
    steps:
      - run: echo "The circleci id is << parameters.to >>"

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  run_command:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pl_id


workflows:
  welcome:
    jobs:
      - run_command
      
          