version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  save_hello_world_output:
    working_directory: ~/hello_world
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach-workspace:
          at: ~/hello_world
      - run: echo "hello world" > output.txt
      - persist_to_workspace:
          root: ~/hello_world
          paths:
            - builds/*

  print_output_file:
    working_directory: ~/hello_world
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_to_workspace:
          at: ~/hello_world/builds/
      - run: cat output.txt

workflows:
  welcome:
    jobs:
      - save_hello_world_output
      - print_output_file
          