version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  run_command:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          return 1
      - run:
          echo "Hello Error!"
          when: on_fail


workflows:
  welcome:
    jobs:
      - run_command
      
          